-- MySQL Script generated by MySQL Workbench
-- Sun Aug 25 19:18:09 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`CSRManager`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CSRManager` (
  `idCSRManager` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  PRIMARY KEY (`idCSRManager`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Academy`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Academy` (
  `idAcademy` INT NOT NULL,
  `AcademyName` VARCHAR(45) NULL,
  `AcademyConnectionID` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `city` VARCHAR(45) NULL,
  `country` VARCHAR(45) NULL,
  `NetacadMemberSince` INT NULL,
  `AcademyLevel` VARCHAR(45) NULL,
  `Academy_Approved_by_CSR` DATETIME NULL,
  `CSRManager_ID` VARCHAR(45) NULL,
  `NumberOfNewStudentsEachYear` INT NULL,
  `Preferred_Language` VARCHAR(45) NULL,
  `Alternative_Language` VARCHAR(45) NULL,
  PRIMARY KEY (`idAcademy`),
  INDEX `fk_Academy_CSRManager1_idx` (`CSRManager_ID` ASC),
  CONSTRAINT `fk_Academy_CSRManager1`
    FOREIGN KEY (`CSRManager_ID`)
    REFERENCES `mydb`.`CSRManager` (`idCSRManager`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Twinning`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Twinning` (
  `idTwinning` INT NOT NULL,
  `Academy1_Initiator` INT NULL,
  `Academy2_Responder` INT NULL,
  `CSRManager_ID` INT NULL,
  `Twinning_Approved_By_CSR` DATETIME NULL,
  PRIMARY KEY (`idTwinning`),
  INDEX `fk_Twinning_CSRManager1_idx` (`CSRManager_ID` ASC),
  INDEX `fk_Twinning_Academy1_idx` (`Academy1_Initiator` ASC),
  CONSTRAINT `fk_Twinning_CSRManager1`
    FOREIGN KEY (`CSRManager_ID`)
    REFERENCES `mydb`.`CSRManager` (`idCSRManager`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Twinning_Academy1`
    FOREIGN KEY (`Academy1_Initiator`)
    REFERENCES `mydb`.`Academy` (`idAcademy`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Twinning_Academy2`
    FOREIGN KEY (`idTwinning`)
    REFERENCES `mydb`.`Academy` (`idAcademy`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Donation_Proposal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Donation_Proposal` (
  `idDonation_Proposal` INT NOT NULL,
  `Academy` INT NULL,
  `Number_Of_Bundle_3_Routers_3_Switches` INT NULL,
  `Number_Of_Bundle_6_Routers_6_Switches` INT NULL,
  `Equipment_Is_Functionnal` TINYINT NULL,
  `Equipment_Is_In_Eligible_List` TINYINT NULL,
  `Bundle_Description` TEXT NULL,
  PRIMARY KEY (`idDonation_Proposal`),
  INDEX `fk_Donation_Proposal_Academy_idx` (`Academy` ASC),
  CONSTRAINT `fk_Donation_Proposal_Academy`
    FOREIGN KEY (`Academy`)
    REFERENCES `mydb`.`Academy` (`idAcademy`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Get_Equipment_Request`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Get_Equipment_Request` (
  `idGet_Equipment_Request` INT NOT NULL,
  `Academy` INT NULL,
  `Bundle_Size_Requested_3_or_6` INT NULL,
  `Estimated_Bundle_Utilization_per_Week` INT NULL,
  `Estimated_Nr_Of_Students_Each_week` INT NULL,
  PRIMARY KEY (`idGet_Equipment_Request`),
  INDEX `fk_Get_Equipment_Request_Academy1_idx` (`Academy` ASC),
  CONSTRAINT `fk_Get_Equipment_Request_Academy1`
    FOREIGN KEY (`Academy`)
    REFERENCES `mydb`.`Academy` (`idAcademy`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Donation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Donation` (
  `idDonation` INT NOT NULL,
  `Donation_Proposal_ID` INT NULL,
  `Get_Equipment_Request_ID` INT NULL,
  `CSRManager_ID` INT NULL,
  PRIMARY KEY (`idDonation`),
  INDEX `fk_Donation_Donation_Proposal1_idx` (`Donation_Proposal_ID` ASC),
  INDEX `fk_Donation_Get_Equipment_Request1_idx` (`Get_Equipment_Request_ID` ASC),
  INDEX `fk_Donation_CSRManager1_idx` (`CSRManager_ID` ASC),
  CONSTRAINT `fk_Donation_Donation_Proposal1`
    FOREIGN KEY (`Donation_Proposal_ID`)
    REFERENCES `mydb`.`Donation_Proposal` (`idDonation_Proposal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Donation_Get_Equipment_Request1`
    FOREIGN KEY (`Get_Equipment_Request_ID`)
    REFERENCES `mydb`.`Get_Equipment_Request` (`idGet_Equipment_Request`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Donation_CSRManager1`
    FOREIGN KEY (`CSRManager_ID`)
    REFERENCES `mydb`.`CSRManager` (`idCSRManager`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
